<?php
/**
 * Implements hook_theme() to add the template definition.
 **/

function subscribe_us_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['subscribe_us_template'] = [
    'template' => 'subscribe-us-template',
    'variables' => [
      'button_contact' => NULL,
    ],
  ];
  return $theme;
}

/**
 * Implements hook_install().
 *
 * Creates some default entries on this module custom table.
 *
 * @see hook_install()
 *
 * @ingroup subscribe_us
 */
function subscribe_us_install() {
  $database = \Drupal::database();
  // Add a default entry.
  $fields = array(
    'email' => 'test@gmail.com',
    'posts' => TRUE,
    'shopping' => TRUE,
  );
  $database->insert('subscribe_us')
    ->fields($fields)
    ->execute();
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 *
 * @ingroup subscribe_us
 */
function subscribe_us_schema() {
  $schema['subscribe_us'] = array(
    'description' => 'Stores subscribe_us data from form.',
    'fields' => array(
      'pid' => array(
        'type' => 'serial',
        'not null' => TRUE,
        'description' => 'Primary Key: Unique person ID.',
      ),
      'email' => array(
        'type' => 'varchar',
        'length' => 30,
        'not null' => TRUE,
        'default' => '',
        'description' => 'Mail of subscriber',
      ),
      'posts' => array(
        'type' => 'boolean',
        'default' => FALSE,
        'description' => 'Subscribe to new posts',
      ),
      'shopping' => array(
        'type' => 'boolean',
        'default' => FALSE,
        'description' => 'Subscribe to new products',
      ),
    ),
    'primary key' => array('pid'),
    'indexes' => array(
      'email' => array('email'),
    ),
  );

  return $schema;
}