<?php
/**
 * Implements hook_theme() to add the template definition.
 **/

function contact_us_theme($existing, $type, $theme, $path) {
  $theme = [];
  $theme['contact_us_template'] = [
    'template' => 'contact-us-template',
    'variables' => [
      'button_contact' => NULL,
    ],
  ];
  return $theme;
}

/**
 * Implements hook_install().
 *
 * Creates some default entries on this module custom table.
 *
 * @see hook_install()
 *
 * @ingroup contact_us
 */
function contact_us_install() {
  $database = \Drupal::database();
  // Add a default entry.
  $fields = array(
    'full_name' => 'Vova',
    'email' => 'test@gmail.com',
    'phone_number' => 'Some test data',
    'order_number' => 'Test',
    'details' => 'Some test data',
  );
  $database->insert('contact_us')
    ->fields($fields)
    ->execute();
}

/**
 * Implements hook_schema().
 *
 * Defines the database tables used by this module.
 *
 * @see hook_schema()
 *
 * @ingroup contact_us
 */
function contact_us_schema() {
  $schema['contact_us'] = [
    'description' => 'Stores contact_us data from form.',
    'fields' => [
      'pid' => [
        'type' => 'serial',
        'description' => 'Primary Key: Unique person ID.',
      ],
      'full_name' => [
        'type' => 'varchar',
        'length' => 30,
        'default' => '',
        'description' => 'A name of sender',
      ],
      'email' => [
        'type' => 'varchar',
        'length' => 30,
        'default' => '',
        'description' => 'Mail of sender',
      ],
      'phone_number' => [
        'type' => 'varchar',
        'length' => 30,
        'default' => '',
        'description' => 'Phone number of sender',
      ],
      'order_number' => [
        'type' => 'varchar',
        'length' => 30,
        'default' => '',
        'description' => 'Order number',
      ],
      'details' => [
        'type' => 'varchar',
        'length' => 255,
        'default' => '',
        'description' => 'Details about order',
      ],
    ],
    'primary key' => ['pid'],
    'indexes' => [
      'full_name' => ['full_name'],
      'email' => ['email'],
    ],
  ];

  return $schema;
}