<?php

/**
* Implements hook_views_query_alter().
*/

function related_products_views_query_alter(Drupal\views\ViewExecutable $view, Drupal\views\Plugin\views\query\Sql $query){
  if ($view->id() == 'related_goods') {
    foreach ($query->where as &$condition_group) {
      foreach ($condition_group['conditions'] as &$condition) {
        if ($condition['field'] == 'commerce_product__field_kind.field_kind_target_id IN(:commerce_product__field_kind_field_kind_target_id[])') {
          $parameter = \Drupal::routeMatch()->getParameter('commerce_product');
          $product = \Drupal\commerce_product\Entity\Product::load((int)$parameter->id());
          $target_arrays = $product->get('field_kind')->getValue();
          $tags = [];
          foreach ($target_arrays as $target_array) {
            $tid = $target_array['target_id'];
            $tags[$tid] = (int)$tid;
          }
          $condition['value'] = [
            ':commerce_product__field_kind_field_kind_target_id[]' => $tags
          ];
        }
      }
    }
  }
}

//INNER JOIN {commerce_product__field_kind} commerce_product__field_kind ON
// commerce_product_field_data.product_id = commerce_product__field_kind.entity_id AND
// commerce_product__field_kind.deleted = '0'
//WHERE ((commerce_product__field_kind.field_kind_target_id IN('1', '2')))

