<?php

use Drupal\views\ViewExecutable;
use Drupal\views\Plugin\views\query\QueryPluginBase;

/*****************************************************************************
 * VIEWS VIEW PRE-PROCESS
 * @param $variables
 *****************************************************************************/
function filter_query_preprocess_views_view(&$variables) {
  $view = $variables['view'];
  $id = $view->storage->id();

  // Handle the Group Travel Listing view
  if($id == 'clothes'){
//    echo('123');
  }
}



/**
 * Implements hook_views_query_alter().
 */
function filter_query_views_query_alter(ViewExecutable $view, QueryPluginBase $query) {

  // Only for MY view..
  if ($view->id() == 'clothes' ) {
//    kint($query);
//    foreach ($query->table_queue as $key=>$item) {
//      $query->table_queue[$key]['join']->extra=array();
//    }
  }
}